name: Push Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_SHA: ${{ github.sha }}
      BUILD_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: docker build -t release ./
      - name: Tagging the Release
        run: docker tag release docker.pkg.github.com/jrtapsell/metabaseautocovid/automatic:$GITHUB_SHA
      - name: Login to GitHub Packages
        run: docker login docker.pkg.github.com -u jrtapsell -p "$GITHUB_TOKEN"
      - name: Push the image
        run: docker push docker.pkg.github.com/jrtapsell/metabaseautocovid/automatic:$GITHUB_SHA
      - name: Run validate on the image
        timeout-minutes: 5
        run: docker run --rm --tmpfs /tmp --read-only release ./python/validate.py
      - name: Tag passing images
        run: docker tag release docker.pkg.github.com/jrtapsell/metabaseautocovid/$(echo ${GITHUB_REF#refs/} | sed 's/heads/branch/' | sed 's/\//:/')
      - name: Push branch releases
        run: docker push docker.pkg.github.com/jrtapsell/metabaseautocovid/$(echo ${GITHUB_REF#refs/} | sed 's/heads/branch/' | sed 's/\//:/')
      - name: Tag release number
        if: github.ref == 'refs/heads/master'
        run: docker tag release docker.pkg.github.com/jrtapsell/metabaseautocovid/metabaseautocovid:$BUILD_ID
      - name: Release release number
        if: github.ref == 'refs/heads/master'
        run: docker push docker.pkg.github.com/jrtapsell/metabaseautocovid/metabaseautocovid:$BUILD_ID
      - name: Tag release latest
        if: github.ref == 'refs/heads/master'
        run: docker tag release docker.pkg.github.com/jrtapsell/metabaseautocovid/metabaseautocovid:latest
      - name: Release release latest
        if: github.ref == 'refs/heads/master'
        run: docker push docker.pkg.github.com/jrtapsell/metabaseautocovid/metabaseautocovid:latest
      - name: Creating release tag
        if: github.ref == 'refs/heads/master'
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions" && git tag -a "v${{ github.run_id }}" -m "Release ${{ github.run_id }}"
      - name: Pushing release tag
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: Create Release
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_id }}"
          release_name: "Release ${{ github.run_id }}"
          body: To Fill Out
          draft: true
          prerelease: false