name: "Daily validation"
on:
  schedule:
    - cron: '0 12 * * *'
jobs:
  check_release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: "Release"
    steps:
    - run: "docker run --rm --tmpfs /tmp --read-only docker.pkg.github.com/jrtapsell/metabaseautocovid/metabaseautocovid:latest ./python/validate.py"