name: "Daily validation"
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  check_release:
    runs-on: ubuntu-latest
    name: "Release"
    steps:
      - name: Login to GitHub Packages
        run: docker login docker.pkg.github.com -u jrtapsell -p "${{ secrets.GITHUB_TOKEN }}"
      - run: "docker pull docker.pkg.github.com/jrtapsell/metabaseautocovid/metabaseautocovid:latest"
      - run: "docker run --rm --tmpfs /tmp --read-only docker.pkg.github.com/jrtapsell/metabaseautocovid/metabaseautocovid:latest ./python/validate.py"